site_name: G-ADOPT Status
site_url: https://gadopt.org/
repo_name: g-adopt
repo_url: https://github.com/g-adopt/g-adopt
theme:
  name: material
  logo: 'images/g_logo.svg'
  favicon: 'images/favicon.ico'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigations.indexes
    - toc.integrate
extra_css:
  - stylesheets/gadopt.css

plugins:
  - gen-files:
      scripts:
        - scripts/gen_mem_pages.py