[project]
name = "gadopt_status"
version = "0.1.0"
description = "Code status endpoint for the g-adopt project"
requires-python = ">=3.10"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-material>=9.6.5",
]